#!/bin/bash
# Quick test script for Share Target functionality

echo "🧪 Testing Share Target Functionality"
echo ""
echo "Method 1: Test with URL Parameter"
echo "---------------------------------"
echo "Open this URL in your browser:"
echo "http://localhost:3000?url=https://www.tiktok.com/@test/video/1234567890"
echo ""
echo "Or replace with a real TikTok URL:"
echo "http://localhost:3000?url=YOUR_TIKTOK_URL_HERE"
echo ""
echo ""
echo "Method 2: Test in Browser Console"
echo "----------------------------------"
echo "1. Open PlanIt: http://localhost:3000"
echo "2. Open browser console (F12)"
echo "3. Run:"
echo "   window.location.href = 'http://localhost:3000?url=https://www.tiktok.com/@test/video/1234567890'"
echo ""
echo ""
echo "Method 3: Test as PWA (Mobile)"
echo "-------------------------------"
echo "1. Build the app: cd client && npm run build"
echo "2. Serve the build folder"
echo "3. Install as PWA on your phone"
echo "4. Share a TikTok URL from TikTok app → PlanIt"
echo ""
echo ""
echo "Current Status:"
echo "✅ Frontend checks for ?url=, ?tiktok_url=, or ?text= parameters"
echo "✅ Auto-extracts when URL detected and user is logged in"
echo "✅ Manifest.json configured for share_target"
echo ""
echo "Note: For full PWA share target, you need HTTPS (not localhost)"

